### ISSUE TITLE
LINK TO PORTFOLIO BROKEN

### ISSUE THREAD

**Issue by hansderly** [jmonto55/Portfolio-V2#9]
Hi, @jmonto55 ,
I think the live link to your portfolio is broken.
When i tried to access it there -> 
![Screenshot 2023-03-27 132518](https://user-images.githubusercontent.com/28353673/228019190-70abdefa-049c-4576-a7f3-9f302dbc7f6c.png)

I got this error message: 
![Screenshot 2023-03-27 132725](https://user-images.githubusercontent.com/28353673/228020083-d92d9fd8-98e6-4ac8-add8-fb1454a31bd6.png)

**Comment by jmonto55** [comment]
Hi, @hansderly thank you for spotting the issue, could you please tell me where is the link portfolio-v2-jmonto55.vercel.app located?, that link corresponds to an old version of the web, I thought I'd updated for the new version everywhere 😰

**Comment by jmonto55** [comment]
nvm brother, I just spotted where the old link was, it is updated now, let me know if you spot anything that could be improved in the portfolio 🦾 @hansderly

**Comment by hansderly** [comment]
sure @jmonto55 , it is in your about section of your repository.
You can see it clearly in the image bellow
![Screenshot 2023-03-27 134043](https://user-images.githubusercontent.com/28353673/228022902-4d7e2465-e4fe-4a25-9138-8a42c924c092.png)

**Comment by hansderly** [comment]
I will @jmonto55 , you did an amazing job
congratulations 🍾👏👏👏
